<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HumusPHPUnitModule\Runner'                     => __DIR__ . '/src/HumusPHPUnitModule/Runner.php',
  'HumusPHPUnitModule\Module'                     => __DIR__ . '/src/HumusPHPUnitModule/Module.php',
  'HumusPHPUnitModule\Controller\IndexController' => __DIR__ . '/src/HumusPHPUnitModule/Controller/IndexController.php',
  'HumusPHPUnitModule\RunnerInterface'            => __DIR__ . '/src/HumusPHPUnitModule/RunnerInterface.php',
  'HumusPHPUnitModule\Version'                    => __DIR__ . '/src/HumusPHPUnitModule/Version.php',
  'HumusPHPUnitModule\Service\RunnerFactory'      => __DIR__ . '/src/HumusPHPUnitModule/Service/RunnerFactory.php',
  'HumusPHPUnitModule\Service\ControllerFactory'  => __DIR__ . '/src/HumusPHPUnitModule/Service/ControllerFactory.php',
);
